name: 'Roblox Place Action'
description: 'Create, delete, and list Roblox places using private API'
author: ''

inputs:
  action:
    description: 'Action to perform: create, delete, or list'
    required: true
  roblosecurity:
    description: 'Roblox .ROBLOSECURITY cookie for authentication'
    required: true
  experience_id:
    description: 'Roblox Experience (Universe) ID'
    required: true
  place_id:
    description: 'Roblox Place ID (required for delete and publish actions)'
    required: false
  api_key:
    description: 'Roblox Open Cloud API Key (required for publish action)'
    required: false
  file_path:
    description: 'Path to .rbxl or .rbxlx file (required for publish action)'
    required: false
  place_name:
    description: 'Name for the new place (optional, for create action, requires api_key)'
    required: false

outputs:
  place_id:
    description: 'Created place ID (for create action)'
    value: ${{ steps.run-action.outputs.place_id }}
  places:
    description: 'JSON array of places (for list action)'
    value: ${{ steps.run-action.outputs.places }}
  success:
    description: 'Whether the publish was successful (for publish action)'
    value: ${{ steps.run-action.outputs.success }}
  version_number:
    description: 'Published version number (for publish action)'
    value: ${{ steps.run-action.outputs.version_number }}

runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      shell: bash
      run: npm install --production
      working-directory: ${{ github.action_path }}

    - name: Run Action
      id: run-action
      shell: bash
      run: node ${{ github.action_path }}/src/index.js
      env:
        INPUT_ACTION: ${{ inputs.action }}
        INPUT_ROBLOSECURITY: ${{ inputs.roblosecurity }}
        INPUT_EXPERIENCE_ID: ${{ inputs.experience_id }}
        INPUT_PLACE_ID: ${{ inputs.place_id }}
        INPUT_API_KEY: ${{ inputs.api_key }}
        INPUT_FILE_PATH: ${{ inputs.file_path }}
        INPUT_PLACE_NAME: ${{ inputs.place_name }}

branding:
  icon: 'box'
  color: 'red'
