name: 'Roblox Place Action'
description: 'Create, delete, and list Roblox places using private API'
author: ''

inputs:
  action:
    description: 'Action to perform: create, delete, or list'
    required: true
  roblosecurity:
    description: 'Roblox .ROBLOSECURITY cookie for authentication'
    required: true
  experience_id:
    description: 'Roblox Experience (Universe) ID'
    required: true
  place_id:
    description: 'Roblox Place ID (required for delete action)'
    required: false

outputs:
  place_id:
    description: 'Created place ID (for create action)'
  places:
    description: 'JSON array of places (for list action)'

runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      shell: bash
      run: npm install --production
      working-directory: ${{ github.action_path }}

    - name: Run Action
      shell: bash
      run: node ${{ github.action_path }}/src/index.js
      env:
        INPUT_ACTION: ${{ inputs.action }}
        INPUT_ROBLOSECURITY: ${{ inputs.roblosecurity }}
        INPUT_EXPERIENCE_ID: ${{ inputs.experience_id }}
        INPUT_PLACE_ID: ${{ inputs.place_id }}

branding:
  icon: 'box'
  color: 'red'
